-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS battleop
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE battleop;

-- USERS TABLE
CREATE TABLE IF NOT EXISTS users(
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 username VARCHAR(32) UNIQUE NOT NULL,
 email VARCHAR(190) UNIQUE NOT NULL,
 pass VARCHAR(255) NOT NULL,
 role ENUM('OWNER','ADMIN','MOD','SUPPORT','AUDITOR') NOT NULL DEFAULT 'ADMIN',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 last_login TIMESTAMP NULL,
 last_ip VARBINARY(16) NULL,
 INDEX(username), INDEX(email)
) ENGINE=InnoDB;

-- PLAYERS TABLE
CREATE TABLE IF NOT EXISTS players(
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 handle VARCHAR(32) UNIQUE NOT NULL,
 email VARCHAR(190) UNIQUE,
 country CHAR(2),
 rating INT DEFAULT 1000,
 coins BIGINT DEFAULT 0,
 banned TINYINT(1) DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(handle), INDEX(email), INDEX(country)
) ENGINE=InnoDB;

-- TOURNAMENTS TABLE
CREATE TABLE IF NOT EXISTS tournaments(
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 title VARCHAR(120) NOT NULL,
 game VARCHAR(64) NOT NULL,
 prize BIGINT DEFAULT 0,
 entry_fee BIGINT DEFAULT 0,
 starts_at DATETIME,
 ends_at DATETIME,
 max_players INT DEFAULT 64,
 status ENUM('DRAFT','OPEN','RUNNING','FINISHED','CANCELLED') DEFAULT 'DRAFT',
 rules TEXT,
 meta JSON,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(game), INDEX(status)
) ENGINE=InnoDB;

-- MATCHES TABLE
CREATE TABLE IF NOT EXISTS matches(
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 tournament_id BIGINT UNSIGNED,
 a_player BIGINT UNSIGNED,
 b_player BIGINT UNSIGNED,
 a_score INT DEFAULT 0,
 b_score INT DEFAULT 0,
 winner BIGINT UNSIGNED NULL,
 played_at DATETIME NULL,
 round INT DEFAULT 1,
 FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,
 FOREIGN KEY (a_player) REFERENCES players(id) ON DELETE SET NULL,
 FOREIGN KEY (b_player) REFERENCES players(id) ON DELETE SET NULL,
 INDEX(tournament_id), INDEX(winner)
) ENGINE=InnoDB;

-- REWARDS TABLE
CREATE TABLE IF NOT EXISTS rewards(
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 player_id BIGINT UNSIGNED NOT NULL,
 amount BIGINT NOT NULL,
 reason VARCHAR(160),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
 INDEX(player_id)
) ENGINE=InnoDB;

-- WALLETS TABLE
CREATE TABLE IF NOT EXISTS wallets(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 player_id BIGINT UNSIGNED NOT NULL,
 type ENUM('DEPOSIT','WITHDRAW','ADJUST') NOT NULL,
 amount BIGINT NOT NULL,
 ref VARCHAR(64),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
 INDEX(player_id), INDEX(type)
) ENGINE=InnoDB;

-- TICKETS TABLE
CREATE TABLE IF NOT EXISTS tickets(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 player_id BIGINT UNSIGNED,
 subject VARCHAR(180) NOT NULL,
 status ENUM('OPEN','IN_PROGRESS','CLOSED') DEFAULT 'OPEN',
 body TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL,
 FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE SET NULL,
 INDEX(status)
) ENGINE=InnoDB;

-- PAGES TABLE
CREATE TABLE IF NOT EXISTS pages(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 slug VARCHAR(80) UNIQUE NOT NULL,
 title VARCHAR(160) NOT NULL,
 body MEDIUMTEXT,
 published TINYINT(1) DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL,
 INDEX(slug), INDEX(published)
) ENGINE=InnoDB;

-- NEWS TABLE
CREATE TABLE IF NOT EXISTS news(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 title VARCHAR(160) NOT NULL,
 body MEDIUMTEXT,
 published TINYINT(1) DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(published)
) ENGINE=InnoDB;

-- SETTINGS TABLE
CREATE TABLE IF NOT EXISTS settings(
 k VARCHAR(64) PRIMARY KEY,
 v JSON NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ANTICHEAT TABLE
CREATE TABLE IF NOT EXISTS anticheat(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 player_id BIGINT UNSIGNED,
 severity TINYINT NOT NULL DEFAULT 1,
 code VARCHAR(32) NOT NULL,
 details JSON,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 resolved TINYINT(1) DEFAULT 0,
 FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE SET NULL,
 INDEX(severity), INDEX(code)
) ENGINE=InnoDB;

-- PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS payments(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 player_id BIGINT UNSIGNED,
 gateway VARCHAR(32),
 type ENUM('DEPOSIT','WITHDRAW') NOT NULL,
 amount BIGINT NOT NULL,
 status ENUM('PENDING','SUCCESS','FAILED','REVIEW') DEFAULT 'PENDING',
 payload JSON,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE SET NULL,
 INDEX(status), INDEX(type), INDEX(gateway)
) ENGINE=InnoDB;

-- AUDIT TABLE
CREATE TABLE IF NOT EXISTS audit(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 actor BIGINT UNSIGNED,
 action VARCHAR(48) NOT NULL,
 entity VARCHAR(48),
 entity_id BIGINT NULL,
 meta JSON,
 ip VARBINARY(16),
 ua VARCHAR(255),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (actor) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(action), INDEX(entity), INDEX(created_at)
) ENGINE=InnoDB;